[MainMenu]
Background=CBack
;0=TiberianSunMenuItem
;1=FirestormMenuItem
2=MainMenuExit
3=Escape
ItemMax=4

[TiberianSunMenuItem]
Type=Image
ID=100
Dim=B03l
Highlighted=B03l-h
HighlightSound=24-I018.AUD
Origin=13,42
ActiveRect=13,42,302,326

[FirestormMenuItem]
Type=Image
ID=101
Dim=B03l
Highlighted=B03l-h
HighlightSound=60-N100.AUD
Origin=326,42
ActiveRect=326,42,302,326

[MainMenuExit]
Type=Image
ID=0
Image=B12e
Highlighted=B12e-h
HighlightSound=CHOICE1.AUD
Origin=0,0
ActiveRect=0,0,140,24

[TiberianSunMenu]
0=TiberianSunLAN
1=TiberianSunSkirmish
2=Back
3=EscapeBack
ItemMax=3

[FirestormMenu]
0=FirestormLAN
1=FirestormSkirmish
2=Back
3=EscapeBack
ItemMax=3

[FirestormLAN]
Type=Image
ID=3
Image=B03l
Highlighted=B03l-h
HighlightSound=60-N112.AUD
Origin=164,205
ActiveRect=164,205,312,30

[FirestormSkirmish]
Type=Image
ID=6
Image=B06s
Highlighted=B06s-h
HighlightSound=60-N114.AUD
Origin=164,295
ActiveRect=164,295,312,30

[TiberianSunLAN]
Type=Image
ID=3
Image=B03l
Highlighted=B03l-h
HighlightSound=24-I012.AUD
Origin=164,205
ActiveRect=164,205,312,30

[TiberianSunSkirmish]
Type=Image
ID=6
Image=B06s
Highlighted=B06s-h
HighlightSound=24-I010.AUD
Origin=164,295
ActiveRect=164,295,312,30

[Escape]
Type=Shortcut
ID=0
Keys=ESC

[Back]
Type=Shortcut
ID=102
Keys=BACKSPACE

[EscapeBack]
Type=Shortcut
ID=102
Keys=ESC

[VersionText]
Type=Version
ID=200
