[CnCNet]
Author=Humble/Skylegend/Xme/NME/Mola/Carnage/Cambria/Trooper/Black/Etc./Etc.
Website=https://github.com/HumbleTS/Balance-Veteran-Patch/wiki/Balance-Veteran-Summary
Version=2.50

; List of changes for Veteran & Balance Patch 2.50


[General]
VeteranRatio=3.5	; must destroy this multiple of self-value to become a veteran [per level]
VeteranCombat=.20	; combat BONUS factor when unit is a veteran
VeteranSpeed=.20	; speed BONUS factor when unit is a veteran
VeteranArmor=.20	; armor BONUS when unit is a veteran
VeteranROF=.20		; rate of fire BONUS when unit is a veteran


; Crate Powerups
[Powerups]
Armor=1,ARMOR,2.0		; armor of nearby objects increased (armor multiplier)
Cloak=1,CLOAK			; enable cloaking on nearby objects
Darkness=0,SHROUDX		; cloak entire radar map
Explosion=0,<none>,500		; high explosive baddie (damage per explosion)
Firepower=1,FIREPOWR,2.0	; firepower of nearby objects increased (firepower multiplier)
HealBase=0,HEALALL		; all buildings to full strength
ICBM=1,CHEMISLE			; nuke missile one time shot
Money=0,MONEY,2000		; a chunk o cash (maximum cash)
Napalm=0,<none>,600		; fire explosion baddie (damage)
Reveal=0,REVEAL			; reveal entire radar map
Speed=1,ARMOR,1.7		; speed of nearby objects increased (speed multiplier)
Squad=0,<none>			; squad of random infantry
Unit=0,<none>			; vehicle
Invulnerability=0,ARMOR,1.0	; invulnerability (duration in minutes)
Veteran=1,VETERAN,1		; veteran upgrade (levels to upgrade)
IonStorm=0,<none>		; initiate ion storm
Gas=0,<none>,100		; tiberium gas (damage for each gas cloud)
Tiberium=0,<none>		; tiberium patch
Pod=1,<none>			; drop pod special


; Ion Storm Strike
[IonWH]
Verses=100%,90%,75%,60%,25%	; was in wrong order due to typo, fixed to damage armor types in order of strength properly



; ***** SHARED STRUCTURES/UNITS *****


; Harvester
[HARV]
ThreatAvoidanceCoefficient=0.32 ; was 0.65 (decreased threat avoidance factor to makes harvesters more responsive near enemies)
EliteAbilities=TIBERIUM_HEAL     ; default was none


; Pavement
[GAPAVE]
Adjacent=5		; was 3 (increased the maximum distance pavement could be placed from a players base structures)


; Light Infantry
[E1]
Trainable=no		; makes it impossible for unit to gain veteran status



; ***** GDI SECTION *****


; ~ GDI STRUCTURES ~


; GDI Gate A
[GAGATE_A]
DeployTime=0.022	; was 0.044 (increased the structure deploy animation)
GateCloseDelay=0.044	; was 0.2 (decreased the delay time for gate to open)


; GDI Gate B
[GAGATE_B]
DeployTime=0.022	; was 0.044 (increased the structure deploy animation)
GateCloseDelay=0.044	; was 0.2 (decreased the delay time for gate to open)


; Ion Cannon Uplink
[GAPLUG3]
Prerequisite=GAPLUG	; was Prerequisite=GAPLUG,GATECH (removed requirement to keep GDI Tech Center to acquire Ion Cannon Uplink add-on)


; Hunter Seeker Control
[GAPLUG2]
Prerequisite=GAPLUG	; was Prerequisite=GAPLUG,GATECH,GAWEAP (removed requirement to have GDI Tech Center & GDI War Factory to acquire Seeker Control add-on)



; ~ GDI UNITS ~


; Disc Thrower
[E2]
Trainable=no		; makes it impossible for unit to gain veteran status


; Jumpjet Infantry
[JUMPJET]
Trainable=no		; makes it impossible for unit to gain veteran status


; Ghost Stalker
[GHOST]
Trainable=yes				; default was no (this needs to be changed to enable upgrades)
Elite=EliteLtRail			; added elite weapon when unit becomes promoted
EliteAbilities=SELF_HEAL,FASTER		; default none (changed 1st upgraded to self healing, 2nd upgrade to improved speed)


; Wolverine
[SMECH]
Elite=EliteAssaultCannon		; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; was VEIN_PROOF (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Titan
[MMCH]
Elite=Elite120mm			; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; was SENSORS (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Hover MLRS
[HVR]
Elite=EliteHoverMissile			; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; was SELF_HEAL (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Disruptor
[SONIC]
EliteAbilities=STRONGER,EXPLODES ; default was EXPLODES (changed 1st upgraded to improved strength, 2nd upgrade to explodes)


; Mammoth Mark II
[HMEC]
Trainable=yes				; default was no (this needs to be changed to enable upgrades)
Elite=EliteMechRailgun			; added elite weapon when unit becomes promoted
EliteAbilities=STRONGER		; default was none (changed 1st upgraded to improved strength)


; Orca Fighter
[ORCA]
Elite=EliteHellfire			; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; default was none (changed 1st upgraded to improved weapon, 2nd upgrade to stronger).


; Orca Bomber
[ORCAB]
Elite=EliteBomb				; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; was RADAR_INVISIBLE (changed 1st upgraded to improved weapon, 2nd upgrade to stronger)



; ***** NOD SECTION *****


; ~ NOD STRUCTURES ~


; NOD Gate A
[NAGATE_A]
DeployTime=0.022	; was 0.044 (increased the structure deploy animation)
GateCloseDelay=0.044	; was 0.2 (decreased the delay time for gate to open)


; NOD Gate B
[NAGATE_B]
DeployTime=0.022	; was 0.044 (increased the structure deploy animation)
GateCloseDelay=0.044	; was 0.2 (decreased the delay time for gate to open)


; Tiberium Waste Facility
[NAWAST]
Strength=1200		; was 400 (increased strength value so it wouldn't die to only 1 bomber with 2 passes)


; Laser fence post
[NAPOST]
Adjacent=5		; was 3 (increased the maximum distance laser fence post can be placed from a base structure)


; Obelisk of Light
[NAOBEL]
Armor=heavy		; was wood (wood armor type too weak vs GDI bombers)
Strength=600		; was 725 (decreased for balancing with Armor upgrade)



; ~ NOD UNITS ~


; Rocket Infantry
[E3]
Trainable=no				; makes it impossible for unit to gain veteran status


; Cyborg
[CYBORG]
Trainable=no				; makes it impossible for unit to gain veteran status


; Cyborg Commando
[CYC2]
Trainable=yes				; default was no (this needs to be changed to enable upgrades)
Elite=EliteCyCannon			; added elite weapon when unit becomes promoted
EliteAbilities=SELF_HEAL,FASTER		; default was none (changed 1st upgraded to self healing, 2nd upgrade to improved speed)


; Attack Buggy
[BGGY]
Elite=EliteRaiderCannon			; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; was CRUSHER (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Attack Cycle
[BIKE]
Elite=EliteBikeMissile			; was HoverMissilie (added elite weapon when unit becomes promoted)
EliteAbilities=FIREPOWER,STRONGER	; was VEIN_PROOF (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Artillery
[ART2]
TooBigToFitUnderBridge=true		; added line of code (unit can absorb damage when stopped on war factory & refinery structures preventing harvester bombs, like MLRS can)
Elite=Elite155mm			; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; was SELF_HEAL (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Deployed Artillery 
[GAARTY]
Elite=Elite155mm			; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; was SELF_HEAL (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Tick Tank
[TTNK]
TooBigToFitUnderBridge=true		; added line of code (unit can absorb damage when stopped on war factory & refinery structures preventing harvester bombs, like titan can)
Armor=heavy				; was light (changed armor type to be comparable to Titan when getting bombed)
Elite=Elite90mm				; was 120mmx (changed elite weapon when unit becomes promoted)
EliteAbilities=FIREPOWER,STRONGER	; was SENSORS (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Deployed Tick Tank 
[GATICK]
Elite=Elite90mm				; was 120mmx (changed elite weapon when unit becomes promoted)
EliteAbilities=FIREPOWER,STRONGER	; was SENSORS (changed 1st upgraded to improved weapon, 2nd upgrade to increased strength)


; Stealth Tank
[STNK]
Strength=230				; was 180 (now same as MLRS)
Armour=wood				; was light (now same as MLRS)
CloakingSpeed=3				; was 5 (cloak speed 3 just dies before getting a shot off)
Turret=Yes				; was no (can Q now)
Elite=EliteDragon			; added elite weapon when unit becomes promoted
EliteAbilities=STRONGER,SELF_HEAL	; was EXPLODES (changed 1st upgraded to increased strength, 2nd upgrade to self healing)


; Weed Eater
[WEED]
ThreatAvoidanceCoefficient=0.00		; was 0.65 (removed threat avoidance factor)


; Harpy
[APACHE]
Elite=EliteHarpyClaw			; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; default was none (changed 1st upgraded to improved weapon, 2nd upgrade to stronger)


; Banshee Fighter
[SCRIN]
Elite=EliteProton			; added elite weapon when unit becomes promoted
EliteAbilities=FIREPOWER,STRONGER	; was RADAR_INVISIBLE (changed 1st upgraded to improved weapon, 2nd upgrade to stronger)


; ***** MISC *****



; Tiberium Fiend
[DOGGIE]
Cost=330
Elite=EliteFiendShard			; added elite weapon when unit becomes promoted
EliteAbilities=STRONGER,SELF_HEAL	; default was none (changed 1st upgraded to increased strength, 2nd upgrade to self healing)


; Adult Visceroid
[VISC_LRG]
Cost=330
Trainable=Yes
Elite=EliteSlimeAttack			; added elite weapon when unit becomes promoted
EliteAbilities=STRONGER,SELF_HEAL	; default was none (changed 1st upgraded to increased strength, 2nd upgrade to self healing)



; ***** Weapons Section *****


; Medic Healing			; improved medic healing
[Heal]
Burst=2				; was 0
Range=4.5			; was 2.83


; Cyborg's Vulcan cannon
[Vulcan3]
Damage=11			; increased damage from 10 to 11


; Wolverine Cannon		; improved Wolverin weapon
[AssaultCannon]
Damage=31			; was 40
Burst=2				; was 1


; Cyborg Commando Plasma Cannon
[CyCannon]
Speed=35				; default was 70 (helps to improve accuracy of projectile without getting in extra shots)


; Obelisk Laser Beam
[LaserFire]
ROF=46			; was 120 (this is essentially half after charge (glow) animation is taken into account)



; ***** Elite Weapons Section *****


; Elite Fiend Shard	; created elite version of standard weapon for Tiberium Fiend
[EliteFiendShard]
Damage=42			; 20% increase from standard weapon
ROF=30
Burst=3
Range=6				; 20% increase from standard weapon
Projectile=DogShard
Speed=25
Warhead=Shard
Report=FIEND2


; Elite Visceroid Attack	; created elite version of standard weapon for Adult Visceroid
[EliteSlimeAttack]
Damage=120			; 20% increase from standard weapon
Range=1.56			; 20% increase from standard weapon
ROF=80
Projectile=Invisible
Speed=25
Warhead=Slimer
Report=VICER1


; Elite Wolverine Cannon	; created elite version of standard weapon for Wolverine
[EliteAssaultCannon]
Damage=37			; 20% increase from standard weapon
Burst=2
ROF=25
Range=6				; 20% increase from standard weapon
Projectile=Invisible
Speed=100
Warhead=SA
Report=TSGUN4


; Elite Titan Weapon		; created elite version of standard weapon for Titan
[Elite120mm]
Damage=84			; 20% increase from standard weapon
ROF=80
Range=8.1			; 20% increase from standard weapon
Projectile=Invisible
Speed=90
Warhead=AP
Report=120MMF
Anim=GUNFIRE
Bright=yes


; Elite Hover Missile		; created elite version of standard weapon for Hover MLRS
[EliteHoverMissile]
Damage=36			; 20% increase from standard weapon
ROF=68
Range=9.6			; 20% increase from standard weapon
Burst=2
Projectile=AAHeatSeeker2
Speed=30
Warhead=AP
Report=HOVRMIS1
MinimumRange=2


; Elite Assault Buggy Cannon	; created elite version of standard weapon for Attack Buggy
[EliteRaiderCannon]
Damage=48			; 20% increase from standard weapon
Range=4.8			; 20% increase from standard weapon
Projectile=Invisible
Speed=100
Warhead=SA
Report=CHAINGN1
Anim=MGUN-N,MGUN-NE,MGUN-E,MGUN-SE,MGUN-S,MGUN-SW,MGUN-W,MGUN-NW


; Elite Bike Missile		; created elite version of standard weapon for Attack Cycle
[EliteBikeMissile]
Damage=48			; 20% increase from standard weapon
ROF=60
Range=6				; 20% increase from standard weapon
Projectile=HeatSeeker
Speed=30
Report=MISL1
Warhead=AP


; Elite Artillery Cannon	; created elite version of standard weapon for Artillery
[Elite155mm]
Damage=180			; 20% increase from standard weapon
ROF=110
MinimumRange=5.00
Projectile=Ballistic
Speed=10
Warhead=ARTYHE
Range=21.60			; 20% increase from standard weapon
Report=120MMF
Anim=GUNFIRE
Lobber=yes


; Elite Tick Tank Weapon	; created elite version of standard weapon for Tick Tank
[Elite90mm]
Damage=43			; 20% increase from standard weapon
ROF=50				; was 80 by default (now same as standard weapon)
Projectile=Cannon
Speed=40
Warhead=AP
Range=8.1			; 20% increase from standard weapon
Report=120MMF			; was 120MMX9 (double shot sound)
Anim=GUNFIRE
Bright=yes


; Elite Stealth Tank Weapon	; created elite version of standard weapon for Stealth Tank
[EliteDragon]
Damage=36			; 20% increase from standard weapon
ROF=50
Burst=2
Range=7.2			; 20% increase from standard weapon
Projectile=AAHeatSeeker2
Speed=25
Warhead=AP
Report=MISL1


; Elite Harpy Vulcan Cannon	; created elite version of standard weapon for Harpy
[EliteHarpyClaw]
Damage=72			; 20% increase from standard weapon
ROF=36
Range=5
Projectile=Invisible2
Speed=100
Warhead=SA
Report=CYGUN1


; Elite Banshee Weapon		; created elite version of standard weapon for Banshee
[EliteProton]
Damage=24			; 20% increase from standard weapon
ROF=3
Range=5
Projectile=ProtonTorpedo
Speed=30
Warhead=AP
Report=scrin5b


; Elite Cyborg Commando Plasma Cannon	; created elite version of standard weapon for Cyborg Commando
[EliteCyCannon]
Damage=180				; 50% increase from standard weapon
ROF=50
Range=8.4				; 20% increase from standard weapon
Projectile=ProtonBlast
Speed=35				; default was 70 (helps to improve accuracy of projectile)
Warhead=PlasmaWH
Report=scrin5b


; Ghost's Elite Rail Gun	; created elite version of standard weapon for Ghost Stalker
[EliteLtRail]
Damage=0			; this should be 0 for railgun shots
AmbientDamage=180		; 20% increase from standard weapon	; use this for the railgun damage field.  Leave damage = 0
ROF=60				; ROF for railgun is tied to the duration (MaxEC) of the railgun particle
Range=7.2			; 20% increase from standard weapon
Projectile=Invisible
Speed=100
Warhead=RailShot2
Anim=GUNFIRE
IsRailgun=true
AttachedParticleSystem=SmallRailgunSys
Report=BIGGGUN1


; Elite Orca Fighter Weapon	; created elite version of standard weapon for Orca Fighter
[EliteHellfire]
Damage=36			; 20% increase from standard weapon
ROF=50
Range=6
Projectile=AAHeatSeeker2 ; was HeatSeeker
Speed=30
Warhead=ORCAAP
Report=ORCAMIS1
Burst=2


; Elite Orca Bomber Weapon	; created elite version of standard weapon for Orca Bomber
[EliteBomb]
Damage=192			; 20% increase from standard weapon
ROF=10  ; was 1
Range=5
Projectile=Cannon2
Speed=0
Warhead=ORCAHE
Floater=yes


; Elite MK2 Weapon		; created elite version of standard weapon for MK2
[EliteMechRailgun]
AmbientDamage=300		; 50% increase from standard weapon (can only 1 shot slightly damage Titan)
Damage=0			; this should be 0 for railgun shots
ROF=60				; ROF for railgun is tied to the duration (MaxEC) of the railgun particle
Range=9.6			; 20% increase from standard weapon
Projectile=Invisible
Speed=100
Warhead=RailShot
Report=RAILUSE5
Anim=GUNFIRE
IsRailgun=true
AttachedParticleSystem=LargeRailgunSys



; ***** PROJECTILES *****


; Cyborg Commando Projecticle
[ProtonBlast]
Proximity=no		; default was yes (disabling prevents projectile exploding before hitting target)
Ranged=no		; default was yes (disabling prevents projectile from running out of fuel)
Acceleration=12		; default was 3 (improve accuracy on moving targets)



; ***** WARHEADS *****


; ORCA Bomber Bomb
[ORCAHE]
Verses=200%,90%,75%,32%,32%	;  Verses = damage value verses various armor types (as percentage of full damage)... ; - vs- none, wood (buildings), light armor, heavy armor, concrete
				; was 100% vs concrete, too overpowered vs deployed Tick Tank (Armor=Concrete)
